### ISSUE TITLE
Context menu dissapear

### ISSUE THREAD

**Issue by JuanDaniel1995** [isaacplmann/angular2-contextmenu#1]
Hello, when i right click the element the context menu pops up but it instantly dissapears. I already found a solution, if you are interested in fix it. Thanks for the library, i like it, it is simple and really awesome.

**Comment by isaacplmann** [comment]
Sure.  Show me your solution.  Either as a PR or just paste in the relevant parts of the code.

**Comment by JuanDaniel1995** [comment]
PR Available here => https://github.com/isaacplmann/angular2-contextmenu/pull/2

**Comment by isaacplmann** [comment]
Does this bug happen for you in the [plunker demo](http://plnkr.co/edit/wpJXpEh4zNZ4uCxTURx2?p=preview)?  If so, what browser are you using?  I can't reproduce it there.

It seems like you're having the document:click event fire right after the contextmenu event fires.  I think the best solution would be to stop that document:click event, but I need more information to know the right place to fix it.

**Comment by JuanDaniel1995** [comment]
Yes, it is happening in that plunker as well when i use Firefox. In Google Chrome is working normally.

**Comment by isaacplmann** [comment]
Evidently this is only a problem on Firefox for the Mac.  Firefox (in general) fires a click event on the document whenever there is a contextmenu event [reference](https://bugzilla.mozilla.org/show_bug.cgi?id=184051).  This is fine on Windows Firefox, because the event order is mousedown, click, contextmenu.  For Mac Firefox, the order is mousedown, contextmenu, click [reference](http://stackoverflow.com/q/30631415/5191105).  And the click causes our context menu to go away.

Possible solutions:
1. Your solution #2 would force every browser that isn't Mac Firefox to click twice to get the context menu to disappear.

2. Ignore document click events for 200 ms after we show the context menu.  If someone holds down the right-click for longer than 200 ms (on Mac Firefox), the context menu will disappear when they release the mouse.  All browsers will be unable to close the context menu for 200 ms after it opens.

3. Do browser detection (I thought we were past this...) and handle Mac Firefox separately.


I think option 2 is probably the best answer.

**Comment by isaacplmann** [comment]
Fixed using solution 2 above in version 0.1.7.  I went with a 400 ms timeout to give slow clicking users some grace.
