### ISSUE TITLE
Do it the angular2 way

### ISSUE THREAD

**Issue by SebastianStehle** [isaacplmann/angular2-contextmenu#10]
Hi,

thank you for your work. I would like to see how it works in the angular2 way. I mean as components.

Making more complex context menus in too complex at the moment. E.g. I don't have the async pipe available in my component. It would be better to define the context menu in the template I think where I can also change the styles and do more complex bindings.

**Comment by isaacplmann** [comment]
Let me make sure I'm understanding what you're asking for:

You would like the context menu configuration object to be an array of components that are passed in, instead of an array of ordinary javascript objects.  The components would need to have public functions for executing the action and for determining whether the action is enabled.  The html of the action would be in the template for the component instead of in an html() function.

This would allow you to use the async pipe in your component (and lots of other things too).

**Comment by SebastianStehle** [comment]
Yes, right. 

I think the configuration model you are using is fine if you have easy context menu's. But when you start dealing with colors, formatting and so on, you get a lot of logic in your component. Angular2 can already handle this very easily within the template.

**Comment by isaacplmann** [comment]
This is a nice feature that I'd like to add, but it might be a while before I implement it.

1. I think it would make sense to have the config object still have `html`, `click` and `enabled` properties.  `html` would then be tested to see if it is a component or a plain function.
2. The template for the context menu would need to change from `<a ... [innerHtml]="html(blah)></a>"` to `<a ...><template #linkContent></template></a>`
3. The template would then be picked up by `ViewChildren` and populated with either the link component or a dummy component that uses the html from the `html()` function.

**Comment by isaacplmann** [comment]
I'm finally getting around to working on this.  I should have something out today.

**Comment by isaacplmann** [comment]
Version 0.2.0 has support for arbitrary components in the context menu items.  See the readme for full details.

```html
<context-menu>
  <template context-menu-item let-item [enabled]="isItemEnabled(item)" (execute)="alert('Hi, ' + $event.item.name); $event.event.preventDefault();">
    Say hi, {{item?.name}}!  <my-component [attribute]="item"></my-component>
    With access to the outside context: {{ outsideValue }}
  </template>
</context-menu>
```
