### ISSUE TITLE
Is there a demo with child menus

### ISSUE THREAD

**Issue by bornie21** [isaacplmann/angular2-contextmenu#28]
I want to display a custom color picker as a child menu like this one http://bladepop.github.io/colorpicker/

**Comment by isaacplmann** [comment]
I don't have child menus implemented, no.  It looks like that color picker is for angular 1.x though.  You'll probably run into issues trying to integrate it with angular 2.

You can put whatever angular 2 components you want inside of a context menu item template though.  You'll probably need to swallow the click event ($event.stopPropagation()) on the color picker component so that the click event doesn't bubble up to the context menu and close it.

**Comment by bornie21** [comment]
Ok thanks, I had noticed that it is for angular 1.x I wanted to implement a custom angular 2 picker of similar style though anyway you did a great job on the context menu and would be nicer to have the child menus too

**Comment by isaacplmann** [comment]
It looks like bootstrap itself (as of 3.x) does not implement submenus in dropdowns. I'm using bootstrap html to allow people to easily drop in bootstrap css if they want or style it themselves.  But that causes problems if I now try to extend bootstrap css to implement submenus.

Do I (1) assume bootstrap styles are already there and cause weird behavior for people that choose to style things themselves or (2) explicitly duplicate the needed styles from bootstrap to make submenus work and then have duplicate and potentially conflicting css for those who use a different version of bootstrap.

I think I'm going to opt to not implement child menus, unless there's a big public outcry.  Closing for now.
