### ISSUE TITLE
how to set CSS Style

### ISSUE THREAD

**Issue by junyun0516** [isaacplmann/angular2-contextmenu#8]
I want to set custom css style without bootstrap. how can i do??

**Comment by isaacplmann** [comment]
The html that is generated for the context menu looks like this:

```html
<div class="dropdown angular2-contextmenu">
  <ul class="dropdown-menu">
    <li><!-- the return value of the html() function for each link goes here --></li>
  </ul>
</div>
```
You can key off of the `angular2-contextmenu` class to create your own styles.  Note that the `ul.dropdown-menu` will have inline styles applied for `position`, `display`, `left` and `top` so that it will be positioned at the cursor when you right-click.

I'll add this information to the readme.

**Comment by isaacplmann** [comment]
There is now an example of styling the context menu in the readme.

**Comment by brianhoy** [comment]
How do you apply the styles to the context menu? I've included the example css (from the readme) using the styleUrls property of the component that contains the <context-menu>, but the styles don't seem to be getting applied. Sorry if this issue isn't really specific to this module, I don't know where else to ask.

**Comment by isaacplmann** [comment]
That would do it.  Or you could set ViewEncapsulation:None to make your styles be global.
